### ISSUE TITLE
updated bib file does not update generated bibliography

### ISSUE THREAD

**Issue by bcaramiaux** [bpiwowar/papercite#102]
When I update the bib file (mybibliography.bib), the generated bibliography does not update. I guess it's a problem of cache but I didn't find a simple way to make it work. How to be sure that papercite is using the current version of "mybibliography.bib" and not an old one? (Note: I tried with the default path and a personalized path, same problem when updating the bib file).

**Comment by bpiwowar** [comment]
When you update your bibliography file, this should be detected and the cache cleared. Unless there is a bug, another possible cause of this behavior is that the timestamp of the uploaded file is not correct (your ftp/sftp client may set an incorrect timestamp). 

As a quick fix, you can clear the cache manually: go in the preferences and click "clear cache".

**Comment by bcaramiaux** [comment]
Thanks for the reply. It is actually working now after clear cache in preferences. Another issue though is that Papercite does not see the new PDF added to the folder papercite-data/pdf/. I think this can be due to the fact that I installed and set up my  wordpress in a tmp folder and then move to the root of my website. Can it be?

**Comment by bpiwowar** [comment]
This should be fixed for a long time now; closing, feel free to re-open if needed
