### ISSUE TITLE
Bold title 

### ISSUE THREAD

**Issue by RegyRegy** [bpiwowar/papercite#105]
How to highlight a title? O would like to make it bold, but in tpl is impossilbe, the @#entry must be modified..

**Comment by RegyRegy** [comment]
i have a solution.. <b>@title@</b> ...

**Comment by bpiwowar** [comment]
So this is solved...

**Comment by RegyRegy** [comment]
yeap, 

@author@
		< br/ >
		< b >@title@< /b >
		< br/ >
		@ ?publisher@@publisher@,@;

without #entry in tpl..
