### ISSUE TITLE
Bibtex special characters \textquoteright \textendash not recognized

### ISSUE THREAD

**Issue by rali-udem** [bpiwowar/papercite#111]
Hi,

Bibtex often uses the special characters 

`{\textendash}` (–) 
`{\textemdash}` (—) 
`{\textquoteright}` (’) 
`{\textquoteleft}` (‘) 

but they are not parsed. Only the code remains, yielding poor results like 

`veille d\textquoterightopportunités sur l\textquoterightInternet`

instead of 

`veille d’opportunités sur l’Internet`

The problem is acute for page numbers: `pp. 1{\textendash}12`, because some exporters use the endash to indicate a range.

See for instance the bibtex here: http://true-european-voter.eu/biblio/export/bibtex/153

Could this be rectified, please?

Thanks.

**Comment by timmli** [comment]
Related to this, `--` is not properly interpreted as en dash (`&ndash;`).
