### ISSUE TITLE
URL in bibtex entry

### ISSUE THREAD

**Issue by rali-udem** [bpiwowar/papercite#113]
I think that issue #21 raises a very valid question and could be a great addition to this (already good) plugin. 

Lots of bibtex entries contain a URL field, which is not rendered by papercite. For instance, Zotero and the Drupal module (https://www.drupal.org/project/biblio) both allow the url field.

It would be really great if this link were added to the bibtex bibliography produced by this plugin. The pdf field does exist, but very often the entry refers to another type of file, or simply to a webpage.

Thanks.

**Comment by kellertuer** [comment]
You can easily write you own `.tpl` file (or adapt an existing one) to render the URL-field by using something like
```
	@?url@
	<a href="@url@" title='Link' class='myLinkStyle'>URL</a>
	@;url@
```
where the name of the link is just URL and this will only show if the URL field is specified.

I for myself use the URL for linking a preprint (in most cases the PDF directly) and die DOI field to link to any Journal.

**Comment by bpiwowar** [comment]
@kellertuer Thanks for answering - As URL is not standard, I think it is better to leave it up to the user (and templates).

**Comment by kellertuer** [comment]
Oh, you're right. I thought it was, because many of my BibTeX-Styles and e.g. also the Typo3 BibTeX-Plugin I am using on my university homepage are using and rendering the URL field. Thanks for the clarification.

**Comment by rali-udem** [comment]
Thank you both for your kind help.
