### ISSUE TITLE
Bibtex toggle causes text to dissapear

### ISSUE THREAD

**Issue by mihalisan** [bpiwowar/papercite#115]
In some browsers bibtex toggle causes text to dissapear (reappears when highlighted!).  Any ideas why?  Here is an example:

![image](https://cloud.githubusercontent.com/assets/15785911/11066818/abb17ee4-87c1-11e5-80dd-c6286fbceb05.png)

1. Click on bibtex (open)
![image](https://cloud.githubusercontent.com/assets/15785911/11066938/1800c168-87c2-11e5-8da4-7c328ba59033.png)

2. Click on bibtex (close) - note text dissapearing and also becoming bold (2014)
![image](https://cloud.githubusercontent.com/assets/15785911/11066841/bf3b9508-87c1-11e5-8a73-d9be0fe455a0.png)

3. Highlight text: (back to normal)
![image](https://cloud.githubusercontent.com/assets/15785911/11066853/c6e61a1c-87c1-11e5-98ef-16375bcb8aa2.png)

Thanks!

**Comment by bpiwowar** [comment]
This is strange. I don’t know comodo dragon but it might be a bug related to this browser. Does it happen with mainstream ones (firefox, chrome, opera, safari, internet explorer, …) ?

Benjamin
> On 10 Nov 2015, at 16:44, mihalisan <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> In some browsers (e.g., comodo dragon) bibtex toggle causes text to dissapear (reappears when highlighted!). Any ideas why? Here is an example:
> 
>  <https://cloud.githubusercontent.com/assets/15785911/11066818/abb17ee4-87c1-11e5-80dd-c6286fbceb05.png>
>  <https://cloud.githubusercontent.com/assets/15785911/11066836/b65295b8-87c1-11e5-92fb-db524df3e03f.png>
>  <https://cloud.githubusercontent.com/assets/15785911/11066841/bf3b9508-87c1-11e5-8a73-d9be0fe455a0.png>
>  <https://cloud.githubusercontent.com/assets/15785911/11066853/c6e61a1c-87c1-11e5-98ef-16375bcb8aa2.png>
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/bpiwowar/papercite/issues/115>.
> 



-- 
http://www.bpiwowar.net/about/contact/ <http://www.bpiwowar.net/about/contact/>

**Comment by mihalisan** [comment]
update: this might have been a comodo dragon issue ( comodo dragon is based on chromium anw) - but for some strange reason it was fixed when I changed the [bibtex file...] command to include a specific template (default-bibshow).   Not sure I can explain why but might be helpful to someone else.

Cheers
