### ISSUE TITLE
Bibshow and bibcite key

### ISSUE THREAD

**Issue by someonehere15** [bpiwowar/papercite#119]
Me again.
Maybe it was also not quite clear, or I didn't understand the documentation, so maybe it doesn't need a separate post. The way I understand: if I give bibshow a bibtex file, and the option key_format=numeric, then papercite automatically assigns a key from 1 increasingly to each reference in the file, so that I can avoid using the long bibtex key, but just use a short number depending on the location of the reference in the file. Did I understand it wrong?
Because on the docs, you mention two types of keys: numeric and cite. If cite is the bibtex key, what is numeric, and how can I use it?

Thanks.

**Comment by bpiwowar** [comment]
Yes, you did not understand clearly, this does not work like this - papercite forgets about the ordering of the entries and just keeps the relationship key to bibtex entry.

The only purpose of bibshow it to allow citations (rather than displaying the whole bibtex file)

**Comment by someonehere15** [comment]
but if "cite" is the bibtex key, what is "key"?

**Comment by bpiwowar** [comment]
OK - documentation is not very clear on that: there is the `key_format` option that just specifies how the citation should be displayed, and that can take two values (numeric - the default, 1, 2, ... - and cite - that displays instead of a number the corresponding bibtex key)
