### ISSUE TITLE
punctuation switch in apa style

### ISSUE THREAD

**Issue by GerhardKa** [bpiwowar/papercite#120]
When listing the bibliography in apa style, at the end of the bib entry title you get the comma before the ending quotation marks (but it should be the other way round: comma after), e.g.,

A. Author, „An example explains itself,“ in Proceedings of ... .

I couldn't easily find in the papercite files where to correct that myself, so here is my request.

Thank you for this plugin!

**Comment by bpiwowar** [comment]
This is the original style ieee style (there are no quotes in apa). You can customize the templates by copying it in the papercite data directory (see the documentation), and then editing the ieee.tpl file (look at the `&quot;` in the format file, e.g.

change

    @?title@&quot;@title@@;@@?journal||volume||number||pages||year@,&quot; @:@.&quot; @;@

to

    @?title@&quot;@title@@;@@?journal||volume||number||pages||year@&quot;, @:@&quot;. @;@

I know the syntax is not really nice... but it is not mine!
