### ISSUE TITLE
Issues with PHP version 7.1 or higher

### ISSUE THREAD

**Issue by member15012018** [bpiwowar/papercite#125]
Papercite when used with new version PHP 7.1, I get the following warning messages. These notices will appear if DEBUG is enabled in WP-CONFIG.PHP. **The warning shows that in future, papercite plugin may not work. Kindly verify if you can update and release a new version.** Thank you.

WARNING NOTICES from WordPress Dashboard

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; PaperciteBibtexPages has a deprecated constructor in webhosting\wp-content\plugins\papercite\lib\BibTex_osbib.php on line 19

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; PaperciteBibtexCreators has a deprecated constructor in webhosting\wp-content\plugins\papercite\lib\bibtex_common.php on line 8

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; PaperciteParseCreators has a deprecated constructor in webhosting\wp-content\plugins\papercite\lib\PARSECREATORS.php on line 22

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; BibtexConverter has a deprecated constructor in webhosting\wp-content\plugins\papercite\bib2tpl\bibtex_converter.php on line 66

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; PaperciteBibtexEntryFormat has a deprecated constructor in webhosting\wp-content\plugins\papercite\bib2tpl\bib2tpl-entry.php on line 10

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Bib2TplHelper has a deprecated constructor in webhosting\wp-content\plugins\papercite\bib2tpl\helper.inc.php on line 48

Notice: Undefined offset: 1 in webhosting\wp-content\plugins\papercite\bib2tpl\bibtex_converter.php on line 438

Notice: Undefined offset: 1 in webhosting\wp-content\plugins\papercite\bib2tpl\bibtex_converter.php on line 438

**Comment by bpiwowar** [comment]
Should be fixed in new version
