### ISSUE TITLE
Pages don't render since the new version 0.5.17

### ISSUE THREAD

**Issue by mderijke** [bpiwowar/papercite#127]
Just installed the new version, 0.5.17, and my wordpress pages that use paper cite no longer render. 

See, for example, https://staff.fnwi.uva.nl/m.derijke/publications/

Or http://www.bpiwowar.net/research/publications/

**Comment by bpiwowar** [comment]
Could you give me more details (code of the page + bib file)  ?

**Comment by bpiwowar** [comment]
That's OK, I can look at my website :-)

**Comment by bpiwowar** [comment]
Actually in my case this was not due to `papercite`, but to the plugin `TableOfContent`

Could you set DEBUG on, and send me the error codes if they are related to papercite, cf: 

https://codex.wordpress.org/Debugging_in_WordPress

**Comment by mderijke** [comment]
Thank you for getting back to me Benjamin!

I was offline for a couple of hours.

Here’s the error code that’s shown:

Parse error: syntax error, unexpected '[', expecting ')' in /data/mdrijke1/WWW/wp-content/plugins/papercite/lib/BibTex_osbib.php on line 514

> Op 11 mei 2018, om 11:07 heeft Benjamin Piwowarski <notifications@github.com> het volgende geschreven:
> 
> Actually in my case this was not due to papercite, but to the plugin TableOfContent
> 
> Could you set DEBUG on, and send me the error codes if they are related to papercite, cf:
> 
> https://codex.wordpress.org/Debugging_in_WordPress
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---
Maarten de Rijke
University of Amsterdam
http://staff.fnwi.uva.nl/m.derijke

**Comment by mderijke** [comment]
Thank you for the fix Benjamin!

> Op 11 mei 2018, om 13:06 heeft mderijke <notifications@github.com> het volgende geschreven:
> 
> Thank you for getting back to me Benjamin!
> 
> I was offline for a couple of hours.
> 
> Here’s the error code that’s shown:
> 
> Parse error: syntax error, unexpected '[', expecting ')' in /data/mdrijke1/WWW/wp-content/plugins/papercite/lib/BibTex_osbib.php on line 514
> 
> > Op 11 mei 2018, om 11:07 heeft Benjamin Piwowarski <notifications@github.com> het volgende geschreven:
> > 
> > Actually in my case this was not due to papercite, but to the plugin TableOfContent
> > 
> > Could you set DEBUG on, and send me the error codes if they are related to papercite, cf:
> > 
> > https://codex.wordpress.org/Debugging_in_WordPress
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> > 
> 
> ---
> Maarten de Rijke
> University of Amsterdam
> http://staff.fnwi.uva.nl/m.derijke
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

---
Maarten de Rijke
University of Amsterdam
http://staff.fnwi.uva.nl/m.derijke
