### ISSUE TITLE
folders for pdf and bib deleted

### ISSUE THREAD

**Issue by miccol** [bpiwowar/papercite#129]
Hi,
thank you for your plugin.
The new update deleted the `pdf `and the `bib `folder, breaking the generation of the page.
According to the new documentation, the files should be in `wp-content/papercite-data `  however this folder does not esist. There is still the old `wp-content/papercite`

**Comment by bpiwowar** [comment]
I guess your folders were located in the plugin folder - they get automatically deleted when the plugin is updated, so this is not a good place to put the files. Just create a folder in `wp-content` named `papercite-data`

**Comment by miccol** [comment]
OK.
Thanks!
