### ISSUE TITLE
papercite is updated but an error occured 

### ISSUE THREAD

**Issue by elisavetgrig** [bpiwowar/papercite#138]
A few weeks ago I updated the papercite plugin and after that, there is the following error: 

Fatal error: Call to undefined function mb_strtolower() in D:\.....\wp-content\plugins\papercite\lib\BibTex_osbib.php on line 198

Do you have any idea how can  I fix it? 

Thank you.

**Comment by bpiwowar** [comment]
I guess php was compiled without `--enable-mbstring`.

you can replace it by `strtolower` (but this won't convert accents).
