### ISSUE TITLE
One source file per entry

### ISSUE THREAD

**Issue by staeglis** [bpiwowar/papercite#140]
Hi,

I have for each bibtex entry a separate file. Is it possible to import all files directly? "[bibtex file=*.bib]" doesn't work.

The PDF file for each bibtex file $name.bib is named $name.pdf. Can I change the mapping easily?

Cheers,
Stefan

**Comment by digfish** [comment]
According to the [documentation about the bibtex shortcode](https://papercite.readthedocs.io/en/latest/usages/) the argument file does not support wildcards. 
The suggestion is to join all the individual .bib into a single one using a command like:
`cat *.bib > all.bib` 
and then use the generated file in the shortcode.
