### ISSUE TITLE
Publishing latest work to WordPress plugin registry

### ISSUE THREAD

**Issue by macguirerintoul** [bpiwowar/papercite#145]
Hey there,

It looks like @digfish has done some work and released up to version 0.6.0 - is there a plan to incorporate those changes and publish them on the WordPress plugin registry? I spent a while trying to fix the regex issue with PHP 7.3 and was about to file a bug, then I realized @digfish had already done it in the other repo.

Thanks!

**Comment by digfish** [comment]
Unfortunately, the wordpress plugin registry is managed by the SVN
repository, which I don't have access to. It will have to be up to
@bpiwowar to do that.


Macguire Rintoul <notifications@github.com> escreveu no dia quarta,
17/07/2019 à(s) 02:25:

**Comment by digfish** [comment]
Unfortunately, the wordpress plugin registry is managed by the SVN repository, which I don't have access to. It will have to be up to @bpiwowar to do that.

**Comment by scrobbleme** [comment]
Any news on this?

**Comment by digfish** [comment]
Hi @scrobbleme ,
I asked @bpiwowar permission for write access to the SVN repository of Wordpress plugin, to update just the main branch (not with my fork). I'm still waiting for his answer.

**Comment by bpiwowar** [comment]
This should be OK now.

best
benjamin

**Comment by digfish** [comment]
Hi
thanks @bpiwowar for letting me have access to the wordpress plugin repo. It has been updated with the last version on github.
Cheers
